import { InteractionResponseType } from 'discord-interactions';
import { DiscordRequest } from '../utils.js';
import { Mistral } from '@mistralai/mistralai';
import { getConversationId, setConversationId, deleteConversationId } from '../utils/conversationStore.js';
import { getOmniAgentId } from '../utils/agentManager.js';

const client = new Mistral({ apiKey: process.env.MISTRAL_API_KEY });

export const data = {
    name: 'chat',
    description: 'Chat with Mistral AI (shared context)',
    options: [
        {
            type: 3, // STRING
            name: 'message',
            description: 'The message to send',
            required: true,
        }
    ],
    type: 1, // CHAT_INPUT
    integration_types: [0, 1],
    contexts: [0, 1, 2],
};

export async function execute(req, res) {
    const { data, token, application_id, channel_id, member, user } = req.body;
    // Use channel_id for context. If DM, channel_id works fine too.
    const contextId = channel_id;

    // User message
    const userMessage = data.options.find(opt => opt.name === 'message').value;
    const authorUsername = member ? member.user.username : user.username;

    // We defer first
    await res.send({
        type: 5, // DEFERRED_CHANNEL_MESSAGE_WITH_SOURCE
    });

    try {
        const payloads = await getChatResponse(userMessage, contextId, authorUsername);
        await sendPayloads(application_id, token, payloads);
    } catch (error) {
        console.error('Error in chat:', error);
        if (error.message && error.message.includes("404")) {
            // Already handled in getChatResponse but good to be safe if reused outside
        }

        const endpoint = `webhooks/${application_id}/${token}/messages/@original`;
        await DiscordRequest(endpoint, {
            method: 'PATCH',
            body: {
                content: `Sorry, I met an error. (Conversation might be reset). Error: ${error.message}`,
            },
        });
    }
}

export async function getChatResponse(userMessage, contextId, authorUsername) {
    try {
        let conversationId = getConversationId(contextId);
        console.log(`[DEBUG] Channel: ${contextId}, Found ConvID: ${conversationId}`);

        // Helper function
        const processOutputs = async (outputs) => {
            const payloads = []; // Array of { content: string, embeds: [] }
            let currentText = `> ${userMessage}\n\n`;
            let currentEmbeds = [];

            // Helper to flush current buffer
            const flush = () => {
                if (!currentText.trim() && currentEmbeds.length === 0) return;

                // Split long messages
                while (currentText.length > 2000) {
                    let splitIndex = currentText.lastIndexOf(' ', 2000);
                    if (splitIndex === -1) splitIndex = 2000;

                    payloads.push({ content: currentText.slice(0, splitIndex), embeds: [] });
                    currentText = currentText.slice(splitIndex);
                }

                if (currentText.trim() || currentEmbeds.length > 0) {
                    payloads.push({ content: currentText, embeds: [...currentEmbeds] });
                }
                currentText = "";
                currentEmbeds = [];
            }

            if (outputs && outputs.length > 0) {
                const lastOutput = outputs[outputs.length - 1];
                if (lastOutput.type === 'message.output' || lastOutput.role === 'assistant') {
                    if (Array.isArray(lastOutput.content)) {
                        for (const part of lastOutput.content) {
                            if (part.type === 'text') {
                                currentText += part.text;
                            } else if (part.type === 'image_url') {
                                currentEmbeds.push({ image: { url: part.image_url.url } });
                                flush(); // Interleave: flush text + this image
                            } else if (part.type === 'tool_file') {
                                try {
                                    // Mistral SDK expects camelCase 'fileId'
                                    const urlResponse = await client.files.getSignedUrl({ fileId: part.fileId });
                                    if (urlResponse && urlResponse.url) {
                                        currentEmbeds.push({
                                            image: { url: urlResponse.url },
                                            footer: { text: "Generated by Mistral OmniBot" }
                                        });
                                        flush(); // Interleave: flush text + this image
                                    } else {
                                        currentText += `\n[Image generated but URL could not be retrieved: ${part.fileName}]`;
                                    }
                                } catch (err) {
                                    console.error("Error getting signed url:", err);
                                    currentText += `\n[Error retrieving image: ${part.fileName}]`;
                                }
                            }
                        }
                    } else {
                        currentText += lastOutput.content;
                    }
                }
            }

            // Flush remaining text
            flush();
            return payloads;
        };


        if (!conversationId) {
            // Start new conversation
            const agentId = await getOmniAgentId();
            const startParams = {
                agentId: agentId,
                inputs: [{ role: 'user', content: `${authorUsername}: ${userMessage}` }]
            };

            const convoResponse = await client.beta.conversations.start(startParams);

            // API returns conversationId (not id)
            conversationId = convoResponse.conversationId || convoResponse.id;
            setConversationId(contextId, conversationId);

            const startPayloads = await processOutputs(convoResponse.outputs);

            if (startPayloads.length === 0) {
                // Fallback
                startPayloads.push({ content: "I'm not sure how to respond to that." });
            }

            return startPayloads;

        } else {
            // Append
            const convoResponse = await client.beta.conversations.append({
                conversationId: conversationId,
                conversationAppendRequest: {
                    inputs: [{ role: 'user', content: `${authorUsername}: ${userMessage}` }]
                }
            });

            const appendPayloads = await processOutputs(convoResponse.outputs);
            if (appendPayloads.length === 0) {
                appendPayloads.push({ content: "I'm not sure how to respond." });
            }

            return appendPayloads;
        }

    } catch (error) {
        console.error('Error in chat:', error);
        if (error.message && error.message.includes("404")) {
            deleteConversationId(contextId); // Assuming deleteConversationId is imported, but it's not. 
            // Wait, looking at original code line 154, it was `deleteConversationId(contextId)` but it wasn't imported in line 4.
            // Wait, let me check imports.
            // import { getConversationId, setConversationId } from '../utils/conversationStore.js';
            // Ah, deleteConversationId was missing from imports in original file view?
            // Let me check my previous file view.
            // Line 4: import { getConversationId, setConversationId } from '../utils/conversationStore.js';
            // Line 154: deleteConversationId(contextId);
            // It seems the original code had a bug or I missed an import.
            // I should attempt to fix this or import it if I can.
            // I'll stick to logic but since I'm refactoring I should probably fix the import too if it exists.
            // For now, I'll allow the error to bubble up or rethrow.
        }
        throw error;
    }
}

// Helper to send interleaved messages
export async function handlePassiveMessage(message) {
    const userMessage = message.content;
    const authorUsername = message.author.username;
    const contextId = message.channel.id;

    // Combine user message with instruction
    // User managed instructions on Agent side
    // Add Timestamp and ID and User ID
    const now = new Date().toLocaleString('es-ES', { timeZone: 'America/Argentina/Buenos_Aires' });
    const fullContent = `[${now}] (ID: ${message.id}) (UID: ${message.author.id}) ${authorUsername}: ${userMessage}`;

    try {
        let conversationId = getConversationId(contextId);
        let outputs = [];

        if (!conversationId) {
            const agentId = await getOmniAgentId();
            // Start new conversation
            const startParams = {
                agentId: agentId,
                inputs: [{ role: 'user', content: fullContent }]
            };
            const convoResponse = await client.beta.conversations.start(startParams);
            conversationId = convoResponse.conversationId || convoResponse.id;
            setConversationId(contextId, conversationId);
            outputs = convoResponse.outputs;
        } else {
            // Append
            const convoResponse = await client.beta.conversations.append({
                conversationId: conversationId,
                conversationAppendRequest: {
                    inputs: [{ role: 'user', content: fullContent }]
                }
            });
            outputs = convoResponse.outputs;
        }

        // Parse Output
        if (outputs && outputs.length > 0) {
            const lastOutput = outputs[outputs.length - 1];
            let contentStr = "";

            if (Array.isArray(lastOutput.content)) {
                // Combine text parts
                contentStr = lastOutput.content.filter(p => p.type === 'text').map(p => p.text).join("");
            } else {
                contentStr = lastOutput.content;
            }


            // Attempt JSON parse
            // Remove markdown code blocks if present
            contentStr = contentStr.replace(/```json/g, '').replace(/```/g, '').trim();

            try {
                const response = JSON.parse(contentStr);

                // Debug Mode
                if (process.env.DEBUG_LUMI === 'true') {
                    console.log("[Lumi Debug JSON]:", JSON.stringify(response, null, 2));
                    // Send JSON to channel (split if too long, though unlikely for this usage)
                    const debugMsg = `\`\`\`json\n${JSON.stringify(response, null, 2)}\n\`\`\``;
                    if (debugMsg.length <= 2000) {
                        await message.channel.send(debugMsg);
                    } else {
                        await message.channel.send(debugMsg.slice(0, 2000)); // Truncate if huge
                    }
                } else {
                    console.log("[Passive Analysis]", response.thought);
                }

                if (response.reaction) {
                    try {
                        const targetId = response.reply_to || message.id; // React to the specific message if indicated, otherwise the trigger message? 
                        // Actually spec says 'reaction' to user message. Usually that means the trigger message.
                        // But if reply_to is another message, it might imply reacting to that.
                        // Let's stick to reacting to the trigger message `message` for now unless logic suggests otherwise.
                        // The example "Input: ... UserA ... Output: reaction" implies reacting to UserA's message (the input).
                        await message.react(response.reaction);
                    } catch (e) {
                        console.error(`Failed to react with ${response.reaction}:`, e.message);
                    }
                }

                if (response.send_text === true) {
                    // Send Typing
                    await message.channel.sendTyping();

                    const textToSend = response.text_content || "."; // Fallback to avoid empty message error

                    // Logic: reply_to takes precedence.
                    if (response.reply_to) {
                        try {
                            const targetMsg = await message.channel.messages.fetch(response.reply_to);
                            await targetMsg.reply(textToSend);
                        } catch (fetchErr) {
                            console.warn(`Could not fetch reply_to message ${response.reply_to}:`, fetchErr.message);
                            // Fallback to channel send if target missing
                            await message.channel.send(textToSend);
                        }
                    } else {
                        // Normal message to channel
                        await message.channel.send(textToSend);
                    }
                }

            } catch (jsonError) {
                console.error("Failed to parse JSON response from Agent:", contentStr);
            }    // Optionally: log to a file or just ignore. 
            // If it fails to parse, we probably shouldn't spam the channel.
        }


    } catch (error) {
        console.error('Error in passive chat:', error);
        if (error.message && error.message.includes("404")) {
            deleteConversationId(contextId);
        }
    }
}
